server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=usuarios-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0

spring.cloud.gateway.routes[1].id=inventario-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/productos/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=0

spring.cloud.gateway.routes[2].id=ventas-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/ventas/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=0

logging.level.org.springframework.cloud.gateway=DEBUG