# 1. Identificación y Puerto
server.port=8083
spring.application.name=ventas-service

spring.datasource.url=jdbc:mysql://localhost:3306/cordillera_ventass?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

feign.client.config.default.error-decoder=com.cordillera.ventas.exception.CustomErrorDecoder